In [ ]:
import numpy as np

In [ ]:
def sigmoid(x):
    return 1/(1 +np.exp(-x))

def softmax(x):
    e=np.exp(x)
    return  e/np.sum(e)

In [ ]:
# 가중치 초깃값 설정
V = np.array([[0.1, 0.3], [0.2, 0.4]])
W = np.array([[0.1, 0.3], [0.2, 0.4]])

# 지도 데이터
t = np.array([[1, 0]])

# 학습률
eta = 0.005

In [ ]:

# 순전파
x = np.array([[1, 0.5]])
y = sigmoid( x.dot(V))
z = softmax (y.dot(W))
print (x, y, z)

[[1.  0.5]] [[0.549834   0.62245933]] [[0.44165237 0.55834763]]


In [ ]:
# 역전파
delta2 = z - t
grad_W = y.T.dot(delta2)
sigmoid_dash = y * (1-y)
delta1 = delta2.dot(W.T) * sigmoid_dash
grad_V = x.T.dot(delta1)
W -= eta * grad_W
V -= eta * grad_V
print(V)
print(W)

[[0.0998618  0.29986879]
 [0.1999309  0.39993439]]
[[0.10153499 0.29846501]
 [0.20173774 0.39826226]]
