In [1]:
import tensorflow as tf

In [2]:
W= tf.Variable (tf.random.normal (shape=[1]))
b= tf.Variable (tf.random.normal (shape=[1]))
print (W, b)

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-0.20603062], dtype=float32)> <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.24075961], dtype=float32)>


In [3]:
def create_linear_model(x):
    return W*x +b    

In [4]:
def create_mse_loss( y_pred, y):
    return tf.reduce_mean( tf.square (y_pred -y))    

In [5]:
optimizer = tf.optimizers.SGD (0.01)

In [6]:
def train_step(x,y):
    with tf.GradientTape() as tape:
      y_pred =create_linear_model(x)
      loss = create_mse_loss (y_pred, y)
      gradients=tape.gradient (loss, [W,b])
      optimizer.apply_gradients (zip(gradients, [W,b]))

In [7]:
x_train=[1,2,3,4]
y_train=[2,4,6,8]

In [10]:
for i in range(20):
    train_step( x_train, y_train)

    x_test = [ 3.5, 5, 5.5, 6 ]
    print (create_linear_model (x_test).numpy())

[ 6.9937687  9.977074  10.971509  11.965943 ]
[ 6.993788  9.977142 10.971594 11.966045]
[ 6.9938064  9.977211  10.97168   11.966148 ]
[ 6.993825  9.97728  10.971765 11.966249]
[ 6.993843   9.977347  10.9718485 11.966351 ]
[ 6.9938617  9.977415  10.971932  11.966451 ]
[ 6.9938793  9.977483  10.972016  11.966551 ]
[ 6.9938984  9.97755   10.9721    11.966651 ]
[ 6.9939165  9.977618  10.972185  11.966752 ]
[ 6.993935  9.977684 10.972267 11.966851]
[ 6.993953  9.977751 10.97235  11.96695 ]
[ 6.993971   9.9778185 10.972434  11.96705  ]
[ 6.993989  9.977883 10.972515 11.967147]
[ 6.9940066  9.97795   10.972598  11.967246 ]
[ 6.994025  9.978016 10.97268  11.967344]
[ 6.994043  9.978083 10.972762 11.967442]
[ 6.9940605  9.978148  10.972844  11.96754  ]
[ 6.9940786  9.978213  10.972925  11.967636 ]
[ 6.994096  9.978278 10.973005 11.967733]
[ 6.994114  9.978344 10.973087 11.96783 ]


In [11]:
summary_writer = tf.summary.create_file_writer ('./tensorboard_log')

In [ ]:
def train_step(x,y):
    with tf.GradientTape() as tape:
      y_pred =create_linear_model(x)
      loss = create_mse_loss (y_pred, y)
      with summary_writer.as_default():
        tf.summary.scalar ('loss', loss, step=optimizer.iterations)
      gradients=tape.gradient (loss, [W,b])
      optimizer.apply_gradients (zip(gradients, [W,b]))

In [ ]:
x_train=[1,2,3,4]
y_train=[2,4,6,8]

In [ ]:
for i in range(1000):
    train_step( x_train, y_train)

    x_test = [ 3.5, 5, 5.5, 6 ]
    print (create_linear_model (x_test).numpy())