https://cs231n.github.io/python-numpy-tutorial/

In [1]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print (a.shape, a.dtype)

(3, 2) int64


In [2]:
print(a[[0, 1, 2], [0, 1, 0]]) 
"""
세상 알았음 ㅋ 
a의 0,1,2행 즉, 전체 행, 0번째 1번째 0번째 즉, 첫째행에서 0열 1, 둘째행에서 1열, 셋째행에서 0열

뒤에 소개됨 Fancy Indexing
"""

[1 4 5]


'\n세상 알았음 ㅋ \na의 0,1,2행 즉, 전체 행, 0번째 1번째 0번째 즉, 첫째행에서 0열 1, 둘째행에서 1열, 셋째행에서 0열\n\n뒤에 소개됨 Fancy Indexing\n'

In [3]:
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

[1 4 5]


In [4]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[2 2]
[2 2]


In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]


In [ ]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a) 

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2) 
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
print( a[bool_idx])

[3 4 5 6]


In [ ]:
# We can do all of the above in a single concise statement:
print(a[a > 2])  

[3 4 5 6]


In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)            

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


**numpy broadcasting기능이 있음**

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [6]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
print(np.reshape(v, (3,1)))
print ("\n")
print(np.reshape(v, (3, 1)) * w)
'''
이건 broadcasting이라고 보기보다 그냥 행렬 곱 연산인 듯
3*1 과 1*2 행렬이 multipulication되면 3*2이 당연하잖아요...
'''

[[1]
 [2]
 [3]]


[[ 4  5]
 [ 8 10]
 [12 15]]


'\n이건 broadcasting이라고 보기보다 그냥 행렬 곱 연산인 듯\n3*1 과 1*2 행렬이 multipulication되면 3*2이 당연하잖아요...\n'

In [7]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
print(x + v)
#요건 broadcasting이 맞음

[[2 4 6]
 [5 7 9]]


In [ ]:
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [ ]:
print(x*2)

[[ 2  4  6]
 [ 8 10 12]]


#이미지작업

imread등 

Scipy upgrade version에서 imread가 import 안되는 문제가 있어서 위 예제는 다른 파일에서 실행

https://github.com/wikibook/pymldg-rev/blob/master/1%EC%9E%A5/1.3%20%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb

In [2]:
import numpy as np

In [3]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [16]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

array3 shape: (5, 2)


In [6]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())


array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [17]:
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print('array3d:\n',array3d.tolist())

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [7]:
# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [8]:
# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


# Fancy Indexing

In [19]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d ,'\n')

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

array2d[[0,1], 2] =>  [3, 6]


In [20]:
array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())
print('\n')
array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]


array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


#Boolean Indexing

In [21]:
array1d= np.arange(1,10)
array3 = array1d[array1d >5]
print(array3)

[6 7 8 9]


In [23]:
boolean_indexes=array1d>5
print(boolean_indexes)

[False False False False False  True  True  True  True]


In [24]:
print(array1d[boolean_indexes])

[6 7 8 9]


# sort(  )  &  org_array.sort(  )

In [2]:
import numpy as np

org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)
# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]


In [3]:
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


#내림차순 정렬

In [4]:
np.sort(org_array)[::-1]

array([9, 5, 3, 1])

In [7]:
array=np.array([[8, 1], 
                   [7, 12]])

In [8]:
#row방향 정렬
np.sort(array, axis=0)

array([[ 7,  1],
       [ 8, 12]])

In [9]:
#column방향 정렬
np.sort(array, axis=1)

array([[ 1,  8],
       [ 7, 12]])

#argsort(  )

In [11]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

print( np.argsort(score_array) )
print('\n')
print( name_array[np.argsort(score_array)])

[0 2 4 1 3]


['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [13]:
#성적 내림차순 정렬
print( name_array[  np.argsort(score_array)[::-1] ])

['Kate' 'Mike' 'Samuel' 'Sarah' 'John']
