In [1]:
import numpy as np

In [7]:
x = np.ones((1, 2, 3))
print (x)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
print (np.transpose(x, (1, 0, 2)) )

[[[1. 1. 1.]]

 [[1. 1. 1.]]]


(2, 1, 3)

In [8]:
np.transpose(x, (1, 0, 2)).shape 

(2, 1, 3)