In [2]:
import numpy as np
x = np.array([ 1, -1, 0, np.infty, -np.inf])

In [3]:
x

array([  1.,  -1.,   0.,  inf, -inf])

In [6]:
print(x/np.infinity)

AttributeError: ignored

In [5]:
print (x/np.infty)

[ 0. -0.  0. nan nan]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [7]:
import datetime as dt
dob = dt.datetime( 2020, 9, 8)
print(dob.strftime("%Y-%m-%d: %A"))

2020-09-08: Tuesday


In [15]:
a = 10
b = 5
print (a %/% b)

SyntaxError: ignored

In [17]:
x = 10
y = 5
print (x % y)

0


In [12]:
paste('g', as.character(10.1),"cc",sep= "+")

SyntaxError: ignored

In [13]:
x

array([  1.,  -1.,   0.,  inf, -inf])

In [14]:
x/0

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ inf, -inf,  nan,  inf, -inf])

In [1]:
import numpy as np

In [2]:
a = np.arange( 1, 10)

In [3]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        , 2.33333333, 2.66666667, 3.        ])

몫 %  나머지 //

R의 경우 %/%  , %%

In [4]:
a%3

array([1, 2, 0, 1, 2, 0, 1, 2, 0])

In [6]:
a//3

array([0, 0, 1, 1, 1, 2, 2, 2, 3])

In [7]:
"""
주석쓸 때
"""

'\n주석쓸 때\n'

type

In [8]:
type (100)

int

In [10]:
type(100.1)

float

In [11]:
bool(23.7)

True

In [15]:
a= 100
c = "my string"

In [16]:
d = str(a) + " " + c
print(d)

100 my string


In [17]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
np.mean(a)

7.0

In [19]:
height = np.array([ 45, 75, 60, 52, np.nan])

In [20]:
np.mean(height)

nan

Nan을 제외하고 평균 nanmean

R에서는 na.rm=T 옵션 세팅한 거와 똑같음

In [21]:
np.nanmean(height)

58.0

np.inf

np.infty

In [22]:
np.inf

inf

In [23]:
np.infty

inf

In [24]:
import datetime as dt

In [25]:
now = dt.datetime.now()
print(now.strftime )

<built-in method strftime of datetime.datetime object at 0x7fc2a3dce990>


In [26]:
now = dt.datetime.now()
print(now.year)
print(now.strftime(" %Y-%m-%d: %A"))

2020
 2020-09-14: Monday


In [43]:
def hello2(obj):
    print("Hello" + obj + " !")

hello2(“Jeong”)
### Spyder에서는 문제없이 되는 것 같음 (교수님은 잘 되심)

SyntaxError: ignored

In [41]:
def hello2(obj):
    print("Hello " + obj + " !")

In [42]:
hello2('Jang')

Hello Jang !


In [32]:
hungry = True

In [34]:
if hungry:
    print("I'm hungry")

I'm hungry
