In [11]:
import pandas as pd
from io import StringIO

csv_data =  \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''

df = pd.read_csv (StringIO(csv_data))
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [16]:
df.isnull().sum(axis=0)

A    0
B    0
C    1
D    1
dtype: int64

In [13]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [17]:
df.dropna(axis=0)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [19]:
df.dropna(thresh=4)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [20]:
df.dropna (subset= ['D'])

A    B    C    D
0  1.0  2.0  3.0  4.0
1  5.0  6.0  NaN  8.0

In [21]:
import numpy as np
from sklearn.impute import SimpleImputer

In [22]:
simr = SimpleImputer (missing_values=np.nan, strategy='mean' )
simr = simr.fit (df.values)
imputed_data = simr.transform (df.values)
imputed_data
#SimpleImputer는 axis 매개변수가 없음. axis=0일 때와 같음 

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [23]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [24]:
# 행 방향으로 대체할 값을 계산하기 위해 
#  FunctionTransformer를 사용
from sklearn.preprocessing import FunctionTransformer
ftr_simlr = FunctionTransformer(lambda X: simr.fit_transform(X.T).T, validate=False)
imputed_data = ftr_simlr.fit_transform(df.values)
imputed_data


array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  6.33333333,  8.        ],
       [10.        , 11.        , 12.        , 11.        ]])

In [30]:
import pandas as pd

df = pd.DataFrame([['green', 'M', 10.1, 'class1'],
                   ['red', 'L', 13.5, 'class2'],
                   ['blue', 'XL', 15.3, 'class1']])

df.columns = ['color', 'size', 'price', 'classlabel']
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

In [31]:
size_mapping = { 'XL':3, 'L':2, 'M':1}

df['size'] = df['size'].map(size_mapping)

df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [32]:
inv_size_mapping = {v: k for k, v in size_mapping.items()}
df['size'].map(inv_size_mapping)

0     M
1     L
2    XL
Name: size, dtype: object